# sudo docker compose up -d --build --force-recreate nginx
# https://myproject.local/

version: '1'

services:
    web:
        build:
            context: ./docker/web
        volumes:
            - ./code/:/usr/src/app/
        container_name: ${PROJECT_NAME}-web
        expose:
            - 8000
        ports:
            - 8000:8000
    nginx:
        build:
            context: ./docker/nginx
            args:
                DEV_DOMAIN: ${DEV_DOMAIN}
                NGINX_SSL: ${NGINX_SSL}
        image: 'nginx:alpine'
        container_name: ${PROJECT_NAME}-nginx
        ports:
            #- '80:80'
            - '443:443'
        volumes:
            - ./code:/code
            - ./logs/nginx/error.log:/var/log/nginx/error_manual.log
            - ./logs/nginx/access.log:/var/log/nginx/access_manual.log